### ISSUE TITLE
Scripting Error With Balthisar Tidy for Work 4.1.1

### ISSUE THREAD

**Issue by 0ldM4cM4n** [balthisar/tidy#5]
When I attempt to use the "Tidy File" option under BBEdit's scripts menu, I get the following error:

A scripting error has occurred:
Not authorized to send Apple events to Balthisar Tidy Service Helper.

Do I possibly need to do something in the "Security & Privacy" prefs pane to fix this?

**Comment by balthisar** [comment]
Version 4.1.4 should hit the App Store in 24 to 48 hours, and will fix this issue.

If you've gotten a pre-release version of 4.1.2, note that you will not get automatic notifications from the App Store; you'll have to go in an manually install it.

**Comment by 0ldM4cM4n** [comment]
Thanks for the heads up, Jim. Much appreciated.

Kind regards,

Bill Kochman
Bill’s Bible Basics
wordweaver777@gmail.com
https://www.billkochman.com

**Comment by 0ldM4cM4n** [comment]
Hey Jim,

As usual, Apple is as slow as snails. It is the morning of the 20th here, and the App Store is still showing 4.1.1.

BTW, I am very surprised to see that no one else has submitted an app review, other than mine from three years ago. Such an excellent app too! :)

Kind regards,

Bill Kochman
Bill’s Bible Basics
wordweaver777@gmail.com
https://www.billkochman.com

**Comment by balthisar** [comment]
Bill, sorry for the delay. The App Store update will be functionally equivalent to what I emailed you; only the version number is different.

Apparently the App Store is taking longer than usual because they’ve identified some type of “fraud” on my account and are threatening to close my developer account. I’m sure it’s a misunderstanding, because, really, fraud?

**Comment by 0ldM4cM4n** [comment]
Hey Jim,

No worries, my friend. Just thought you should know. Fraud? I am actually dealing with a real case of fraud on PayPal right now. I hope I get my money back. :(

But, my gosh. I am so sick of automated security systems which police humans. With all of the false positives, it is a real pain in the butt on the social networks in which I participate. I am always being requested to confirm my identity, to change my password multiple times, etc. It grows old quickly. But, what can you expect of modern, imperfect, automated technology.

Kind regards,

Bill Kochman
Bill’s Bible Basics
wordweaver777@gmail.com
https://www.billkochman.com

**Comment by balthisar** [comment]
I'll close this, as Apple have finally allowed release. The "fraud" was having two applications with the same icon, apparently.

**Comment by 0ldM4cM4n** [comment]
Hey Jim,

Oh my! Guess what you wrote to me on September 16th?:

>> If you've gotten a pre-release version of 4.1.2, note that you will not get automatic notifications from the App Store; you'll have to go in and manually install it.

I forgot all about that, so I’ve been using 4.1.2 ever since you emailed it to me on September 15th.

So, I just logged in to the App Store and discovered that it is now up to 4.2.0, which I just now installed.

Thanks for the reminder, and thanks again for all your hard work. Balthisar Tidy for Work continues to be a real time saver for me.

Kind regards from Guam,

Bill Kochman
Bill’s Bible Basics
wordweaver777@gmail.com
https://www.billkochman.com

**Comment by 0ldM4cM4n** [comment]
Hello Jim,

It is hard to believe that it has been nearly a year and a half since I last wrote to you. You will be happy to know that I continue to use Balthisar Tidy for Work on a regular basis in the development of my two websites.

Being as you are a macOS app developer, I am reaching out to you in regards to a special request I have.

Very briefly, due to the blatant discrimination and censorship which Christians and Conservatives experience on the liberal social networks, in November of 2020, I started my own social network called Christian Social Network.

Until just recently, the site was only accessible via a desktop or laptop computer using a standard web browser. Well, you could visit it on a phone using a web browser, but it would not look right, being as the site is not tailored for mobile devices.

However, recently, I paid a company to have both iOS and Android apps made for my site. Currently, I am in the final stages of submitting the iOS version of the CSNet app to Apple’s App Store Connect website so that my app can undergo the review process, and hopefully be added to the App Store in the near future.

Therein lies the problem, Jim.

I spent over an hour today submitting app screenshots, and carefully answering Apple’s pile of technical questions. I am sure that you already know the drill, but it was all very new to me, because I am not a programmer or an app developer.

Anyway, I ran into one snag, and it is the ONLY thing that is preventing Apple from accepting my request for app review.

Apple is requesting app screenshots which are taken on an iPhone with a 5.5” display. I did some quick online research, and this includes the 6 Plus, 6s Plus, 7 Plus and 8 Plus. The problem is that I do not own any of these models, and I don’t know anyone who does. I only own an iPhone Xs Max. As an app developer yourself, I am hoping that you have access to one of these models. If you do, I am requesting the following:

I assume that you already have the TestFlight app installed on your iPhone. Well, assuming that you even use an iPhone. :)

If so, I would like to request that you allow me to send you an email invitation to be a beta tester on the App Store Connect site, so that you can install version 1.0 build 3 of the CSNet app on your iPhone.

Once you do that, all I will need is less than an hour of your time to take a series of screenshots of different areas of the CSNet site. I can give you the login credentials for a beta tester account so that you can take the required screenshots. You can then email the screenshots to me.

IMPORTANT: One of Apple’s requirements is that your iPhone be fully charged when you take these screenshots. I don’t know why that is exactly, but they make the rules.

In fact, I can send you a zipped archive of the screenshots I took on my iPhone Xs Max, and then you can take the same screenshots on your iPhone. There are ten screenshots in all.

That is all that I am asking of you, Jim. If you are able to do this for me, and are willing to do this for me, please let me know at your earliest convenience.

Thank you so much, Jim.

Kind regards in Christ,

Bill Kochman, Administrator
Bill’s Bible Basics / Christian Social Network
***@***.***
https://www.billkochman.com
https://www.csnet.live <https://www.csnet.live/>

**Comment by balthisar** [comment]
Hi Bill,

It’s been some time!

I’m not an iOS developer, so all I have is my personal iPhone, and it has a 6.68” screen, and not 5.5. I could take a screenshot if it’s useful.

It might be easier to use the iOS simulator in Xcode, though. It takes screenshots easily, and on current version of Xcode, it simulates devices back to the iPhone 8 with all of the many different screen sizes.

**Comment by 0ldM4cM4n** [comment]
Hello again Jim,

Thank you for the suggestion, but I don’t think that approach would work, even if I could figure out how to do it.

For one thing, it is my understanding that the screenshots must be taken on an actual 5.5” iPhone, and not merely be a simulation in the Simulator. To prove my point, in Apple’s app submission guidelines, it specifically states that the screenshots must show that the iPhone is fully charged. I don’t understand why that it is necessary, but Apple makes the rules.

Based on the online images I have looked at, when you use the Simulator, it shows the word “Simulator” in the title bar at the top of the Simulator window, thus revealing that it is not a real iPhone.

Lastly, I am not the one actually building the app. Another company is doing it for me. As such, I do NOT have the actual project files on my iMac’s hard drive,. Thus, I cannot compile the project on my hard drive. If there is a way to download all of the project files from the App Store Connect site, and into Xcode 12.4 on my iMac, I don’t know how to do it. In fact, I am not even sure if the project files are even on the App Store Connect website. I am very new to all of this.

In other words, my understanding is that I would have to compile the project files in Xcode on my iMac, and then run the compiled app in Simulator. To begin with, I don’t even know how to compile project files in Xcode. I am not a programmer.

As I said, even if I could do the above, the Simulator plainly shows in its window that it is a simulation, and not a real iPhone, and I think Apple would bulk at that.

The way it works is this: Whenever there is a new test build of my app on the App Store Connect site, it is downloaded to my iPhone using another app called TestFlight. I and my friends then just use the test build on our phones and check it for problems and bugs.

Kind regards,

Bill Kochman, Administrator
Bill’s Bible Basics / Christian Social Network
***@***.***
https://www.billkochman.com
https://www.csnet.live

**Comment by balthisar** [comment]
Hi Bill,

If you want screenshots from my big screen, I’m happy to do it.

FWIW, here’s a screenshot from the simulator. It looks just like the screenshots on the App Store. Whoever your developer is should be able to take correct-sized screen shots in the simulator for you.

Let me know if I can help.

**Comment by 0ldM4cM4n** [comment]
Hello Jim,

Thanks for your response.

Okay, I am really confused here.

First of all, no image was included with your latest email.

Second, I in fact already wrote to the company that is making the two apps for me — iOs and Android -- and they declined to help, stating that making screenshots of my iOS app running on an iPhone is not included in the purchase price, and that submitting my app to the App Store Connect site is solely my responsibility as well, and not theirs.

Lastly, I honestly don’t understand what you are proposing.

The screen shots I need to submit must show different screens of my app running on an iPhone with a 5.5” display, which includes the 6 Plus, 6s Plus, 7 Plus and 8 Plus.

I am attaching the ten screenshots that i already submitted which were taken on my Xs Max. If you can take these same screenshots in the 8 Plus Simulator, that would be great.

Ha! Scratch that idea. I just tried to send a zipped archive that is only 14.5 MB in size, and your mail server rejected the message stating that it was too big.

Anyway, what I don’t understand is how you can take said screenshots, unless I make you a beta tester on the App Store Connect site, so that you can download my app to your 6.68” screen iPhone, using the TestFlight app.

Even if you do that, how will that help you to take screenshots of my app running in the 8 Plus simulator?

Sorry for my confusion, but as I said, I am not a programmer.

If you can in fact do what I need, then please explain more clearly to me what I have to do on my end to make that happen.

Thanks so much! Iook forward to hearing from you again.

Kind regards,

Bill Kochman, Administrator
Bill’s Bible Basics / Christian Social Network
***@***.*** ***@***.***>
https://www.billkochman.com <https://www.billkochman.com/>
https://www.csnet.live <https://www.csnet.live/>
